GET http://localhost:8080/first-jsf-app/api/v1/product

###

POST  http://localhost:8080/first-jsf-app/api/v1/product
Content-Type: application/json

{
  "description": "Description 2",
  "name": "Product REST 2",
  "price": 102.00,
  "categoryId": 1
}

###

PUT http://localhost:8080/first-jsf-app/api/v1/product
Content-Type: application/json

{
  "id": 5,
  "description": "Description 2222",
  "name": "Product REST 2222",
  "price": 102.00,
  "categoryId": 1
}

###

DELETE http://localhost:8080/first-jsf-app/api/v1/product/6